package me.dreamdevs.slender.api;

public enum Setting {

	AUTO_JOIN_MODE,
	SHOW_ARENA_JOIN_MESSAGE,
	MESSAGE_TYPE,
	SLENDER_SKIN,
	OWNED_SLENDER_SKINS,
	DARKNESS_FLICKER,
	FLASHLIGHT_REALISTIC,
	MUSIC_ENABLED;

}