package me.dreamdevs.slender.game;

import me.dreamdevs.slender.SlenderMain;
import me.dreamdevs.slender.api.game.Difficulty;
import me.dreamdevs.slender.api.game.Role;
import me.dreamdevs.slender.database.data.GamePlayer;
import net.kyori.adventure.text.Component;
import net.kyori.adventure.text.format.NamedTextColor;
import org.bukkit.Bukkit;
import org.bukkit.Location;
import org.bukkit.Sound;
import org.bukkit.entity.Player;
import org.bukkit.event.EventHandler;
import org.bukkit.event.Listener;
import org.bukkit.event.player.PlayerMoveEvent;
import org.bukkit.event.player.PlayerToggleSneakEvent;
import org.bukkit.potion.PotionEffect;
import org.bukkit.potion.PotionEffectType;
import org.bukkit.scheduler.BukkitTask;

import java.util.HashMap;
import java.util.Map;
import java.util.UUID;
import java.util.concurrent.ThreadLocalRandom;

/**
 * Stealth system: tracks virtual noise generated by players.
 * Running, jumping, and collecting items creates noise that attracts SlenderMan.
 * Sneaking silences footsteps and slightly stabilizes sanity.
 */
public class StealthManager implements Listener {

    private final Map<UUID, Double> noiseLevels = new HashMap<>();
    private final Map<UUID, Long> lastNoiseTime = new HashMap<>();
    private final Map<UUID, Long> lastWarningTime = new HashMap<>();
    private final double NOISE_DECAY_RATE = 0.5;
    private final double NOISE_SPRINT = 8.0;
    private final double NOISE_WALK = 1.0;
    private final double NOISE_JUMP = 5.0;
    private final double SNEAK_NOISE = 0.0;

    private BukkitTask decayTask;

    public void start(Arena arena) {
        if (decayTask != null) decayTask.cancel();

        decayTask = Bukkit.getScheduler().runTaskTimer(SlenderMain.getInstance(), () -> {
            long now = System.currentTimeMillis();
            noiseLevels.keySet().removeIf(uuid -> {
                long last = lastNoiseTime.getOrDefault(uuid, 0L);
                if (now - last > 5000) return true;
                double current = noiseLevels.getOrDefault(uuid, 0.0);
                noiseLevels.put(uuid, Math.max(0.0, current - NOISE_DECAY_RATE));
                return false;
            });
        }, 0L, 20L);
    }

    @EventHandler
    public void onMove(PlayerMoveEvent event) {
        Player player = event.getPlayer();
        GamePlayer gamePlayer = SlenderMain.getInstance().getPlayerManager().getPlayer(player);
        if (gamePlayer == null || !gamePlayer.isInArena()) return;

        Arena arena = (Arena) gamePlayer.getArena();
        if (arena == null || arena.getPlayers().get(player) != Role.SURVIVOR) return;

        if (event.getFrom().distanceSquared(event.getTo()) < 0.01) return;

        UUID uuid = player.getUniqueId();
        double noise;

        if (player.isSneaking()) {
            noise = SNEAK_NOISE;
        } else if (player.isSprinting()) {
            noise = NOISE_SPRINT;
            
            // Phase 4: HARD Mode Tripping Mechanic
            if (arena.getCurrentDifficulty() == Difficulty.HARD) {
                // Since PlayerMoveEvent fires constantly, we use a very very low chance
                if (ThreadLocalRandom.current().nextInt(1000) < 3) {
                    player.addPotionEffect(new PotionEffect(PotionEffectType.SLOWNESS, 60, 2));
                    player.addPotionEffect(new PotionEffect(PotionEffectType.BLINDNESS, 40, 0));
                    player.playSound(player.getLocation(), Sound.ENTITY_PLAYER_HURT, 1f, 1f);
                    player.sendMessage(me.dreamdevs.slender.api.utils.ColourUtil.colorizeToComponent("&cYou tripped in the darkness!"));
                }
            }
        } else {
            noise = NOISE_WALK;
        }

        addNoise(uuid, noise);
    }

    @EventHandler
    public void onSneak(PlayerToggleSneakEvent event) {
        if (!event.isSneaking()) return;

        Player player = event.getPlayer();
        GamePlayer gamePlayer = SlenderMain.getInstance().getPlayerManager().getPlayer(player);
        if (gamePlayer == null || !gamePlayer.isInArena()) return;

        Arena arena = (Arena) gamePlayer.getArena();
        if (arena == null) return;

        UUID uuid = player.getUniqueId();
        double current = noiseLevels.getOrDefault(uuid, 0.0);
        noiseLevels.put(uuid, Math.max(0.0, current - 2.0));

        player.sendActionBar(Component.text("Sneaking - You are silent", NamedTextColor.GREEN));
    }

    public void addNoise(UUID uuid, double amount) {
        double current = noiseLevels.getOrDefault(uuid, 0.0);
        noiseLevels.put(uuid, Math.min(20.0, current + amount));
        lastNoiseTime.put(uuid, System.currentTimeMillis());

        // Action bar warnings (throttled to every 2 seconds)
        long now = System.currentTimeMillis();
        long lastWarn = lastWarningTime.getOrDefault(uuid, 0L);
        if (now - lastWarn < 2000) return;

        Player player = Bukkit.getPlayer(uuid);
        if (player == null || !player.isOnline()) return;

        double noise = noiseLevels.getOrDefault(uuid, 0.0);
        if (noise > 5.0) {
            player.sendActionBar(Component.text("⚠ You're making too much noise...", NamedTextColor.RED));
            player.playSound(player.getLocation(), Sound.BLOCK_NOTE_BLOCK_BASS, 0.3f, 0.3f);
            lastWarningTime.put(uuid, now);
        } else if (noise > 2.0) {
            player.sendActionBar(Component.text("You're being heard...", NamedTextColor.YELLOW));
            lastWarningTime.put(uuid, now);
        }
    }

    public void addNoise(Player player, double amount) {
        addNoise(player.getUniqueId(), amount);
    }

    public double getNoise(UUID uuid) {
        return noiseLevels.getOrDefault(uuid, 0.0);
    }

    public double getNoise(Player player) {
        return getNoise(player.getUniqueId());
    }

    public double getDetectionRadius(UUID uuid) {
        return getNoise(uuid) * 1.5;
    }

    public boolean isDetectable(UUID uuid, Location slenderLocation) {
        double noise = getNoise(uuid);
        if (noise <= 0) return false;

        Player player = Bukkit.getPlayer(uuid);
        if (player == null || !player.isOnline()) return false;

        double dist = player.getLocation().distance(slenderLocation);
        return dist <= getDetectionRadius(uuid);
    }

    public void clearNoise(UUID uuid) {
        noiseLevels.remove(uuid);
        lastNoiseTime.remove(uuid);
        lastWarningTime.remove(uuid);
    }

    public void stop() {
        if (decayTask != null) {
            decayTask.cancel();
            decayTask = null;
        }
        noiseLevels.clear();
        lastNoiseTime.clear();
        lastWarningTime.clear();
    }
}
